name: Code quality

on:
  push:
  workflow_dispatch:

jobs:
  type-checking:
    name: Type checking
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: pnpm tsc -b

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: pnpm lint

  tests:
    name: Tests
    runs-on: ubuntu-latest
    container: node:18

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tests
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: pnpm test
        env:
          DB_URL: postgresql://postgres:postgres@postgres/test
