name: Deploy to GitHub Pages

on:
  push:
    branches: ['master']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - run: pnpm build
        working-directory: packages/client
        env:
          VITE_APP_BASE_URL: /
          VITE_APP_SERVER_URL: ${{ vars.SERVER_URL }}

      - run: cp dist/index.html dist/404.html
        working-directory: packages/client

      - uses: actions/configure-pages@v3

      - uses: actions/upload-pages-artifact@v1
        with:
          path: packages/client/dist

      - uses: actions/deploy-pages@v2
        id: deployment
